spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot_erudio
    username: root
    password: Flamengo10@
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true