spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/rest_with_spring_boot_erudio
    username: postgres
    password: 123456
  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
