version: '3.1'

services:
  db:
    container_name: "mysql"
    image: mysql:5.7
    volumes:
      - mysql-volume:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Flamengo10@
    ports:
      - "3306:3306"

volumes:
  mysql-volume:
    external: true