spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/rest_with_spring_boot_erudio
    username: root
    password: 123456
  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: true